### ISSUE TITLE
[Request] Have just one minimal summary table listing min/max/mean times and number of runs

### ISSUE THREAD

**Issue by kaushalmodi** [disruptek/golden#17]
See the `hyperfine` output just for comparison -- [ref][1]

[1]: https://gitter.im/nim-lang/Nim?at=5df11ce3fc88886bad07b3b5

**Comment by kaushalmodi** [comment]
Thanks. The `--brief` switch works.

I only have one minor comment.. can you add one echo to let the user know that `golden` is working on something..

e.g. If I do `golden --brief ./mybin`, the terminal will be forever stalled. May be it should error out saying that the `-i=N` parameter is mandatory?

**Comment by disruptek** [comment]
Hmm, good point, but you can interrupt the process and get whatever statistics are available.  Maybe it makes more sense to simply output a warning when using `--brief` so the user knows not to expect anything until normal termination according to other options?
